package com.example.trivianico.model

data class Questions(
    val question: String,
    val correctOption: String,
    val incorrectOption1: String,
    val incorrectOption2: String,
    val incorrectOption3: String,
    val category: Category,
    val diff: Diff,
)

enum class Category {
    Geografia,
    Arte,
    Historia,
    Entretenimiento,
    Ciencias,
    Deportes
}

enum class Diff {
    Easy,
    Normal,
    Hard
}


val questionsList: List<Questions> = listOf(

    //Geografía--------------------------------------------

    Questions(
        "¿Cuál es el río más caudaloso del mundo?",
        "Amazonas",
        "Nilo",
        "Tajo",
        "Mississipí",
        Category.Geografia,
        Diff.Easy
    ),
    Questions(
        "¿Cuál es el monte más alto del mundo?",
        "Everest",
        "Teide",
        "Kanchenjunga",
        "Manaslu",
        Category.Geografia,
        Diff.Easy
    ),
    Questions(
        "¿Cómo se llama la línea vertical imaginaria a partir del cual se miden las longitudes y que divide el mundo en dos mitades?",
        "Meridiano de Greenwich",
        "Línea del Ecuador",
        "Norte",
        "Sur",
        Category.Geografia,
        Diff.Easy
    ),
    Questions(
        "¿Cuál es la capital de Canadá?",
        "Ottawa",
        "Vancouver",
        "Toronto",
        "Mont-real",
        Category.Geografia,
        Diff.Easy
    ),
    Questions(
        "¿Dónde podemos encontrar la Casa Rosada?",
        "Argentina",
        "EEUU",
        "Colombia",
        "Mexico",
        Category.Geografia,
        Diff.Easy
    ),
    Questions(
        "¿Cúantas comunidades autónomas hay en España?",
        "17",
        "16",
        "18",
        "20",
        Category.Geografia,
        Diff.Normal
    ),
    Questions(
        "¿Cuál es el país de mayor tamaño del mundo?",
        "Rusia",
        "China",
        "Brasil",
        "Vaticano",
        Category.Geografia,
        Diff.Normal
    ),
    Questions(
        "¿Cuál es la capital de Filipinas?",
        "Manila",
        "Bangkok",
        "Pekin",
        "Filipinas DC",
        Category.Geografia,
        Diff.Normal
    ),
    Questions(
        "¿Cuál es el país europeo del que provienen las familias de la mayor parte de los habitantes de Argentina?",
        "Italia",
        "España",
        "Portugal",
        "Francia",
        Category.Geografia,
        Diff.Normal
    ),
    Questions(
        "¿Cuál es la capital de Nueva Zelanda?",
        "Aukland",
        "Sydney",
        "Queenstown",
        "Wellington",
        Category.Geografia,
        Diff.Normal
    ),
    Questions(
        "¿Cuántos estados forman parte de Estados Unidos?",
        "50",
        "54",
        "33",
        "51",
        Category.Geografia,
        Diff.Hard
    ),
    Questions(
        "¿En qué país hay un mayor número de pirámides?",
        "Sudán",
        "Egipto",
        "Marruecos",
        "Sudafrica",
        Category.Geografia,
        Diff.Hard
    ),
    Questions(
        "¿Cuál es la cordillera de montañas más larga del mundo?",
        "Los Andes",
        "Himalaya",
        "Montañas Rocosas",
        "De la Costa",
        Category.Geografia,
        Diff.Hard
    ),
    Questions(
        "¿Cuál es la ciudad más fría del mundo?",
        "Oymyakon (Rusia)",
        "Siberia (Rusia)",
        "Harbin (China)",
        "Winnipeg (Canadá)",
        Category.Geografia,
        Diff.Hard
    ),
    Questions(
        " ¿Qué continente se encuentra en los 4 hemisferios?",
        "Africa",
        "América",
        "Europa",
        "Oceanía",
        Category.Geografia,
        Diff.Hard
    ),

    //Arte--------------------------------------

    Questions(
        "¿Quién escribió la Ilíada y la Odisea?",
        "Homero",
        "Bart",
        "Maggie",
        "Lisa",
        Category.Arte,
        Diff.Easy
    ),
    Questions(
        "¿Quién pintó el “Guernica”?",
        "Picasso",
        "Velazquez",
        "Goya",
        "Zurbarán",
        Category.Arte,
        Diff.Easy
    ),
    Questions(
        "¿De qué estilo arquitectónico es la catedral de Notre Dame?",
        "Gótico",
        "Barroco",
        "Renacentista",
        "Románico",
        Category.Arte,
        Diff.Easy
    ),
    Questions(
        "¿Qué nombre tenía el caballo de Don Quijote de la Mancha?",
        "Rocinante",
        "Blanco",
        "Roach",
        "Sardinilla",
        Category.Arte,
        Diff.Easy
    ),
    Questions(
        "¿Qué nombre tenía el caballo de Don Quijote de la Mancha?",
        "Rocinante",
        "Blanco",
        "Roach",
        "Sardinilla",
        Category.Arte,
        Diff.Easy
    ),
    Questions(
        "¿Quién pintó la famosa obra 'La última cena'?",
        "Leonardo da Vinci",
        "Pablo Picasso",
        "Vincent van Gogh",
        "Michelangelo",
        Category.Arte,
        Diff.Normal
    ),
    Questions(
        "¿Cuál de las siguientes corrientes artísticas se caracteriza por el uso de colores vibrantes y formas geométricas?",
        "Cubismo",
        "Impresionismo",
        "Renacimiento",
        "Romanticismo",
        Category.Arte,
        Diff.Normal,
    ),
    Questions(
        "¿En qué ciudad puedes encontrar la famosa escultura 'La Sirenita'?",
        "Copenhague",
        "París",
        "Roma",
        "Nueva York",
        Category.Arte,
        Diff.Normal,
    ),
    Questions(
        "¿Qué famoso artista surrealista es conocido por sus pinturas oníricas con relojes derretidos?",
        "Salvador Dalí",
        "Frida Kahlo",
        "Joan Miró",
        "René Magritte",
        Category.Arte,
        Diff.Normal,
    ),
    Questions(
        "¿Cuál de las siguientes obras es conocida por ser una de las más famosas esculturas renacentistas y representa a un hombre desnudo de proporciones perfectas?",
        "David",
        "Piedad",
        "El Nacimiento de Venus",
        "La Última Cena",
        Category.Arte,
        Diff.Normal,
    ),
    Questions(
        "¿Cuál de las siguientes obras es conocida por su técnica de sfumato, creando una transición suave entre los colores y las sombras?",
        "La Mona Lisa",
        "La Noche Estrellada",
        "El Jardín de las Delicias",
        "Las Meninas",
        Category.Arte,
        Diff.Hard,
    ),
    Questions(
        "¿Quién fue el arquitecto responsable de la construcción de la Catedral de Notre-Dame en París, conocida por su estilo gótico?",
        "Auguste Perret",
        "Antoni Gaudí",
        "Giotto di Bondone",
        "Viollet-le-Duc",
        Category.Arte,
        Diff.Hard,
    ),
    Questions(
        "¿Cuál de las siguientes esculturas es una obra maestra del Renacimiento italiano y representa la figura bíblica de David?",
        "David",
        "El Pensador",
        "La Victoria",
        "Estatua ecuestre",
        Category.Arte,
        Diff.Hard,
    ),
    Questions(
        "¿Qué movimiento artístico del siglo XX se caracteriza por la representación de objetos y figuras de manera distorsionada y fragmentada?",
        "Cubismo",
        "Fauvismo",
        "Expresionismo",
        "Suprematismo",
        Category.Arte,
        Diff.Hard,
    ),
    Questions(
        "¿Quién fue el pintor flamenco conocido por sus obras surrealistas y simbolistas, como 'El jardín de las delicias'?",
        "Hieronymus Bosch",
        "Pieter Bruegel el Viejo",
        "Jan van Eyck",
        "Hans Memling",
        Category.Arte,
        Diff.Hard,
    ),

    //Historia------------------------------------------

    Questions(
        "¿Quién fue el primer presidente de la democracia española tras el franquismo?",
        "Adolfo Suárez",
        "Isabel Díaz Ayuso",
        "Perro Sanxe",
        "Leopoldo Calvo Sotelo",
        Category.Historia,
        Diff.Easy
    ),
    Questions(
        "¿En qué año el hombre pisó la Luna por primera vez?",
        "1969",
        "1968",
        "1967",
        "Nunca",
        Category.Historia,
        Diff.Easy
    ),
    Questions(
        "¿Quién fue el primer presidente de Estados Unidos?",
        "George Washington",
        "Bill Russel",
        "Barack Obama",
        "Franklin D. Roosevelt",
        Category.Historia,
        Diff.Easy
    ),
    Questions(
        "¿Qué carabela no volvió del viaje en el que Colón arribó a América por primera vez?",
        "Santa María",
        "Niña",
        "Pinta",
        "Going Merry",
        Category.Historia,
        Diff.Easy
    ),
    Questions(
        "¿Quiénes fueron, según la leyenda, los dos hermanos fundadores de la ciudad de Roma?",
        "Rómulo y Remo",
        "Rémulo y Rome",
        "Roma y Remo",
        "Rómulo y Roma",
        Category.Historia,
        Diff.Easy
    ),
    Questions(
        "¿La invasión de qué fortaleza por parte de los revolucionarios es considerada como el punto de inicio de la Revolución Francesa?",
        "La toma de la Bastilla",
        "Desembarco de Normandía",
        "Las guerras Napoléonicas",
        "El desembarco del Rey",
        Category.Historia,
        Diff.Normal
    ),
    Questions(
        "¿Cuánto duró la Guerra de los Cien Años?",
        "116 años",
        "100 años",
        "99 años",
        "117 años",
        Category.Historia,
        Diff.Normal
    ),
    Questions(
        "¿En qué año se creó la Organización de las Naciones Unidas?",
        "1945",
        "1942",
        "1950",
        "1955",
        Category.Historia,
        Diff.Normal
    ),
    Questions(
        "¿Cómo se apellidaban los dos exploradores que dieron la primera vuelta al mundo?",
        "Magallanes-Elcano",
        "Marco-Polo",
        "Elcano-Colón",
        "Magallanes-Polo ",
        Category.Historia,
        Diff.Normal
    ),
    Questions(
        "¿Quién era el gran ministro británico cuando la India Británica fue sacudida por la hambruna de Bengala?",
        "Winston Churchill",
        "Margaret Thatcher",
        "Sir Anthony Eden",
        "Boris Johnson",
        Category.Historia,
        Diff.Normal
    ),
    Questions(
        "¿Cuál es la narración épica más antigua de la historia, encontrada en tablillas de arcilla sobre las que se usó escritura cuneiforme?",
        "Epopeya de Gilgamesh",
        "La Santa Biblia",
        "La Divina Comedia",
        "El cantar del Mio Cid",
        Category.Historia,
        Diff.Normal
    ),
    Questions(
        "¿Qué faraón egipcio es conocido por haber intentado que su imperio pasase del politeísmo al monoteísmo a través del culto al dios Atón?",
        "Akenatón",
        "Ramsés II",
        "Cleopatra",
        "Anedjib",
        Category.Historia,
        Diff.Hard
    ),
    Questions(
        " ¿Qué emperador romano es conocido entre otras cosas por haber intentado someterse a operaciones de cambio de sexo?",
        "Marco Aurelio Antonino Augusto",
        "Tiberius Iulius Caesar",
        "Marcus Opellius Macrinus",
        "Lucius Septimius Severus",
        Category.Historia,
        Diff.Hard
    ),
    Questions(
        " ¿En qué idioma están escritos los manuscritos más antiguos pertenecientes a la parte de la Biblia que hoy conocemos como Nuevo Testamento?",
        "Griego antiguo",
        "Hebreo antiguo",
        "Latin",
        "Celta",
        Category.Historia,
        Diff.Hard
    ),
    Questions(
        "¿Cuándo se inventó la escritura?",
        "En el IV milenio a.C",
        "Hace 20 mil años",
        "En el año 0",
        "Hace 37854 años",
        Category.Historia,
        Diff.Hard
    ),
    Questions(
        "¿Contra quiénes se enfrentaron los griegos en las Guerras Médicas del siglo V a.C.?",
        "Los persas",
        "Los celtas",
        "Los hebreos",
        "Los hunos",
        Category.Historia,
        Diff.Hard
    ),

    //Entretenimiento--------------------------

    Questions(
        "¿Cuál de los siguientes actores interpreta a Iron Man en las películas del Universo Cinematográfico de Marvel?",
        "Robert Downey Jr.",
        "Chris Evans",
        "Chris Hemsworth",
        "Mark Ruffalo",
        Category.Entretenimiento,
        Diff.Easy,
    ),
    Questions(
        "¿Quién es la autora de la exitosa serie de libros 'Harry Potter'?",
        "J.K. Rowling",
        "Stephen King",
        "George R.R. Martin",
        "Suzanne Collins",
        Category.Entretenimiento,
        Diff.Easy,
    ),
    Questions(
        "¿Cuál es el título de la película de animación que sigue las aventuras de Elsa y Anna en un reino de hielo?",
        "Frozen",
        "Moana",
        "Zootopia",
        "Coco",
        Category.Entretenimiento,
        Diff.Easy,
    ),
    Questions(
        "¿Qué banda de pop británica lanzó éxitos como 'Yellow', 'Fix You' y 'Viva la Vida'?",
        "Coldplay",
        "The Beatles",
        "One Direction",
        "Queen",
        Category.Entretenimiento,
        Diff.Easy,
    ),
    Questions(
        "¿Cuál es el nombre del mago protagonista de la serie de libros y películas 'Fantastic Beasts'?",
        "Newt Scamander",
        "Albus Dumbledore",
        "Gellert Grindelwald",
        "Rubeus Hagrid",
        Category.Entretenimiento,
        Diff.Easy,
    ),
    Questions(
        "¿Cuál de las siguientes series de televisión sigue las vidas de los habitantes de Hawkins enfrentándose a fenómenos paranormales?",
        "Stranger Things",
        "The Mandalorian",
        "The Witcher",
        "Breaking Bad",
        Category.Entretenimiento,
        Diff.Normal,
    ),
    Questions(
        "¿Quién es la actriz principal en la película 'Birds of Prey', interpretando a Harley Quinn?",
        "Margot Robbie",
        "Gal Gadot",
        "Scarlett Johansson",
        "Emma Stone",
        Category.Entretenimiento,
        Diff.Normal,
    ),
    Questions(
        "¿Cuál de las siguientes películas ganó el premio a la Mejor Película en los Premios de la Academia 2020?",
        "Parasite",
        "Joker",
        "1917",
        "One Piece Film Red",
        Category.Entretenimiento,
        Diff.Normal,
    ),
    Questions(
        "¿En qué película de superhéroes aparece por primera vez el personaje de Black Panther del Universo Cinematográfico de Marvel?",
        "Captain America: Civil War",
        "Black Panther",
        "Avengers: Infinity War",
        "Thor: Ragnarok",
        Category.Entretenimiento,
        Diff.Normal,
    ),
    Questions(
        "¿Cuál es el nombre del actor que interpretó a Geralt de Rivia en la serie de Netflix 'The Witcher'?",
        "Henry Cavill",
        "Jason Momoa",
        "Tom Holland",
        "Chris Pratt",
        Category.Entretenimiento,
        Diff.Normal,
    ),
    Questions(
        "En una película, dirigida por Christopher Nolan, ¿cuál es el término utilizado para describir el acto de implantar una idea en la mente de alguien sin que se dé cuenta?",
        "Inception",
        "Deception",
        "Subception",
        "Reception",
        Category.Entretenimiento,
        Diff.Hard,
    ),
    Questions(
        "En la serie de televisión 'Black Mirror', ¿cuál es el nombre del episodio interactivo lanzado en 2018 donde los espectadores toman decisiones clave?",
        "Bandersnatch",
        "White Christmas",
        "San Junipero",
        "Nosedive",
        Category.Entretenimiento,
        Diff.Hard,
    ),
    Questions(
        "En la película 'Blade Runner 2049', ¿quién interpreta al replicante llamado 'K'?",
        "Ryan Gosling",
        "Jared Leto",
        "Harrison Ford",
        "Dave Bautista",
        Category.Entretenimiento,
        Diff.Hard,
    ),
    Questions(
        "En la película 'Parasite', ganadora del Premio de la Academia a la Mejor Película en 2020, ¿cuál es el nombre de la familia adinerada?",
        "Park",
        "Kim",
        "Chung",
        "Lee",
        Category.Entretenimiento,
        Diff.Hard,
    ),
    Questions(
        "En la serie de televisión 'The Boys', ¿cuál es el nombre del superhéroe con la habilidad de regeneración extrema y una actitud sarcástica?",
        "Billy Butcher",
        "Homelander",
        "The Deep",
        "Translucent",
        Category.Entretenimiento,
        Diff.Hard,
    ),
    Questions(
        "¿Cuál es el nombre del elemento químico con el símbolo 'O' y número atómico 8?",
        "Oxígeno",
        "Oro",
        "Hierro",
        "Plata",
        Category.Ciencias,
        Diff.Easy,
    ),
    Questions(
        "¿Cuál es el planeta más cercano al Sol en nuestro sistema solar?",
        "Mercurio",
        "Venus",
        "Marte",
        "Júpiter",
        Category.Ciencias,
        Diff.Easy,
    ),
    Questions(
        "¿Cuál es la unidad básica de la estructura de los organismos vivos?",
        "Célula",
        "Átomo",
        "Molécula",
        "Tejido",
        Category.Ciencias,
        Diff.Easy,
    ),
    Questions(
        "¿Cuál es la fuerza que mantiene a los objetos en la Tierra y les da peso?",
        "Gravedad",
        "Electromagnetismo",
        "Fuerza nuclear fuerte",
        "Fuerza centrífuga",
        Category.Ciencias,
        Diff.Easy,
    ),
    Questions(
        "¿Cuál es el proceso por el cual las plantas producen su propio alimento utilizando la luz del sol?",
        "Fotosíntesis",
        "Respiración",
        "Digestión",
        "Transpiración",
        Category.Ciencias,
        Diff.Easy,
    ),
    Questions(
        "¿Cuál es la partícula subatómica con carga positiva que se encuentra en el núcleo de un átomo?",
        "Protón",
        "Electrón",
        "Neutrón",
        "Quark",
        Category.Ciencias,
        Diff.Normal,
    ),
    Questions(
        "¿Cuál es el proceso mediante el cual una célula se divide en dos células hijas idénticas?",
        "Mitosis",
        "Meiosis",
        "Fotosíntesis",
        "Replicación",
        Category.Ciencias,
        Diff.Normal,
    ),
    Questions(
        "¿Cuál es la velocidad de la luz en el vacío?",
        "299,792 km/s",
        "150,000 km/s",
        "500,000 km/s",
        "200,000 km/s",
        Category.Ciencias,
        Diff.Normal,
    ),
    Questions(
        "¿Cuál es la principal función del sistema nervioso central en el cuerpo humano?",
        "Procesar información",
        "Transportar oxígeno",
        "Regular la temperatura",
        "Producir energía",
        Category.Ciencias,
        Diff.Normal,
    ),
    Questions(
        "¿Cuál es la teoría científica que explica la expansión acelerada del universo después del Big Bang?",
        "Teoría de la Inflación Cósmica",
        "Teoría del Multiverso",
        "Teoría del Estado Estacionario",
        "Teoría de la Relatividad General",
        Category.Ciencias,
        Diff.Hard,
    ),
    Questions(
        "En la física de partículas, ¿cuál es el nombre de la partícula subatómica descubierta en el Gran Colisionador de Hadrones en 2012?",
        "Bosón de Higgs",
        "Quark Top",
        "Leptón Tau",
        "Mesón Pión",
        Category.Ciencias,
        Diff.Hard,
    ),
    Questions(
        "¿Cuál es el nombre del proceso mediante el cual una estrella masiva colapsa bajo su propia gravedad y forma un objeto extremadamente denso?",
        "Supernova",
        "Pulsar",
        "Agujero Negro",
        "Neutrón Estelar",
        Category.Ciencias,
        Diff.Hard,
    ),
    Questions(
        "En la biología molecular, ¿cuál es el nombre del proceso mediante el cual se copia la información genética del ADN a ARN?",
        "Transcripción",
        "Replicación",
        "Traducción",
        "Mutación",
        Category.Ciencias,
        Diff.Hard,
    ),
    Questions(
        "¿Cuál es el nombre del fenómeno cuántico donde dos partículas están entrelazadas y el estado de una afecta instantáneamente al estado de la otra, incluso si están separadas por grandes distancias?",
        "Entrelazamiento Cuántico",
        "Túneles Cuánticos",
        "Difusión Cuántica",
        "Superposición Cuántica",
        Category.Ciencias,
        Diff.Hard,
    ),

    //Deportes---------------------------------------

    Questions(
        "¿Cuál es el deporte en el que los jugadores compiten por anotar puntos golpeando una pelota con un palo en un campo dividido en hoyos?",
        "Golf",
        "Tenis",
        "Fútbol",
        "Baloncesto",
        Category.Deportes,
        Diff.Easy,
    ),
    Questions(
        "¿Cuántos balones de oro posee Lionel Messi?",
        "8",
        "1",
        "7",
        "5",
        Category.Deportes,
        Diff.Easy,
    ),
    Questions(
        "¿Cuál es el nombre del evento deportivo que se celebra cada cuatro años y reúne a atletas de todo el mundo compitiendo en una variedad de deportes?",
        "Juegos Olímpicos",
        "Copa Mundial",
        "Campeonato Mundial",
        "Super Bowl",
        Category.Deportes,
        Diff.Easy,
    ),
    Questions(
        "¿En qué deporte los equipos compiten para avanzar una pelota hacia la zona de anotación del oponente y anotar touchdowns?",
        "Fútbol Americano",
        "Rugby",
        "Críquet",
        "Hockey sobre hielo",
        Category.Deportes,
        Diff.Easy,
    ),
    Questions(
        "¿Cuál es el deporte acuático en el que los participantes navegan sobre una tabla y son impulsados por las olas?",
        "Surf",
        "Esquí Acuático",
        "Vela",
        "Remo",
        Category.Deportes,
        Diff.Easy,
    ),
    Questions(
        "¿En qué deporte se utiliza una red dividida por una cuerda y una pelota, y los jugadores intentan pasar la pelota sobre la red sin que el equipo contrario la devuelva?",
        "Voleibol",
        "Tenis de Mesa",
        "Bádminton",
        "Balonmano",
        Category.Deportes,
        Diff.Normal,
    ),
    Questions(
        "¿Cuál es el nombre del torneo de tenis que se celebra anualmente en Londres y es uno de los cuatro torneos de Grand Slam?",
        "Wimbledon",
        "US Open",
        "Roland Garros",
        "Australian Open",
        Category.Deportes,
        Diff.Normal,
    ),
    Questions(
        "¿Cuál es el equipo de fútbol brasileño más exitoso que ha ganado numerosos títulos, incluyendo la Copa Libertadores y la Copa Intercontinental?",
        "Santos FC",
        "Flamengo",
        "Corinthians",
        "Palmeiras",
        Category.Deportes,
        Diff.Normal,
    ),
    Questions(
        "En el baloncesto, ¿cuántos puntos vale un tiro libre lanzado desde la línea de tiros libres?",
        "1 punto",
        "2 puntos",
        "3 puntos",
        "4 puntos",
        Category.Deportes,
        Diff.Normal,
    ),
    Questions(
        "¿Cuál es el nombre del evento de ciclismo que abarca tres semanas y es conocido por sus etapas de montaña, contrarreloj y llanas?",
        "Tour de Francia",
        "Giro de Italia",
        "Vuelta a España",
        "Tour de Suiza",
        Category.Deportes,
        Diff.Normal,
    ),
    Questions(
        "En el cricket, ¿cuál es el término utilizado para describir un lanzamiento en el que la pelota gira hacia el bateador después de tocar el suelo?",
        "Googly",
        "Yorker",
        "Bouncer",
        "Doosra",
        Category.Deportes,
        Diff.Hard,
    ),
    Questions(
        "En el golf, ¿cuál es el nombre de la competición anual entre equipos europeos y estadounidenses que se celebra cada dos años?",
        "Ryder Cup",
        "Presidents Cup",
        "Walker Cup",
        "Solheim Cup",
        Category.Deportes,
        Diff.Hard,
    ),
    Questions(
        "¿Cuál es el nombre del evento de ciclismo de ruta que se celebra anualmente en Italia y es conocido por sus rutas desafiantes y montañosas?",
        "Giro de Italia",
        "Tour de Francia",
        "Vuelta a España",
        "Milán-San Remo",
        Category.Deportes,
        Diff.Hard,
    ),
    Questions(
        "En el deporte olímpico de esgrima, ¿cuál es el nombre de la técnica defensiva en la que se desvía el ataque del oponente con un giro de la hoja?",
        "Parry",
        "Lunge",
        "Riposte",
        "Feint",
        Category.Deportes,
        Diff.Hard,
    ),
    Questions(
        "En el mundo del automovilismo, ¿cuántas carreras conforman el campeonato de Fórmula 1 en una temporada típica?",
        "21 carreras",
        "18 carreras",
        "24 carreras",
        "16 carreras",
        Category.Deportes,
        Diff.Hard,
    )

)